FROM adoptopenjdk/openjdk11:armv7l-debian-jdk-11.0.5_10-slim

ENV ENV docker

WORKDIR /opt/FredBoat

COPY fredboat.yml /opt/FredBoat/fredboat.yml
COPY common.yml /opt/FredBoat/common.yml
COPY FredBoat.jar /opt/FredBoat/FredBoat.jar

EXPOSE 1356

ENTRYPOINT ["java", "-Xmx128m", "-jar", "FredBoat.jar"]
